name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 */4 * * * # Every 4 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: make setup

      - name: Run Python script to generate HTML
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USER_LIST: ${{ secrets.USER_LIST }}
          DURATION_IN_DAYS: 5
          PAGE_DATA_COUNT: 5
          START_DATE: ${{ secrets.START_DATE }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}

      - name: Prepare build assets
        run: |
          mkdir -p ./build/assets
          cp -r ./assets/. ./build/assets/.

      # --- PR Preview Deploy ---
      - name: Deploy PR Preview to Netlify
        if: github.event_name == 'pull_request'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './build'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy preview for PR #${{ github.event.pull_request.number }}"
          alias: "pr-${{ github.event.pull_request.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # --- Production Deploy ---
      - name: Deploy to Netlify (Production)
        if: startsWith(github.ref, 'refs/heads/main')
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
